# PyTorch

PyTorch is a Python package that's similar to Numpy in some ways, in that it lets us control a lot of numbers very efficiently. 

Because it does this through the use of the GPU, it's also a platform for deep learning researchers to develop their models. 

(Most of these notes are taken from [here](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#getting-started))

In [2]:
import torch
print(torch.__version__)

0.4.0


# Tensors

## Tensor Construction

Tensors are PyTorch's data objects. They are similar to Numpy's ndarrays, in that they are used to model vectors and matrices. They can also be constructed in similar ways, and have many dimensions.

In [4]:
x = torch.empty(5, 3)
print(x)

tensor(1.00000e-38 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0003,  0.0000],
        [ 0.0000,  1.1388,  0.0000]])


In [88]:
torch.range(1, 24, dtype=torch.int).view(4, 6)

tensor([[  1,   2,   3,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12],
        [ 13,  14,  15,  16,  17,  18],
        [ 19,  20,  21,  22,  23,  24]], dtype=torch.int32)

In [6]:
r = torch.rand(2,2,3)
print(r)

tensor([[[ 0.1114,  0.6349,  0.1065],
         [ 0.4953,  0.7803,  0.5675]],

        [[ 0.1447,  0.0838,  0.1870],
         [ 0.6516,  0.6291,  0.8846]]])


In [37]:
zeros = torch.zeros((5,5), dtype=torch.int32)
print(zeros)

tensor([[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]], dtype=torch.int32)


You can construct a tensor based on another tensor, meaning, the new tensor will have the same dtype and size

In [24]:
randslikezeros = torch.rand_like(zeros, dtype=torch.float)

randslikezeros

tensor([[ 0.8895,  0.4604,  0.8066,  0.7537,  0.8705],
        [ 0.7349,  0.0958,  0.3979,  0.9729,  0.1502],
        [ 0.8739,  0.3825,  0.3066,  0.0313,  0.8822],
        [ 0.7536,  0.4793,  0.8594,  0.8890,  0.8149],
        [ 0.2471,  0.5409,  0.5639,  0.1955,  0.6056]])

In pytorch, the shape attribute and size method give us the same output (but its probably a better idea to use `size()`)

In [34]:
print(randslikezeros.shape)
print(randslikezeros.size())

torch.Size([5, 5])
torch.Size([5, 5])


## Tensor Operations

It comes as no surprise that tensor operations are carried out in an element-wise fashion. To resize, call `torch.view()`

In [106]:
x = torch.range(1,10).view(5,2)
x

tensor([[  1.,   2.],
        [  3.,   4.],
        [  5.,   6.],
        [  7.,   8.],
        [  9.,  10.]])

In [107]:
y = x + torch.range(1,10).view(5,2)
y

tensor([[  2.,   4.],
        [  6.,   8.],
        [ 10.,  12.],
        [ 14.,  16.],
        [ 18.,  20.]])

You can also use the add function, for the same operation. Use the `out` argument to assign the result to a variable

In [108]:
res = torch.empty(5, 2)
torch.add(x, y, out=res)

tensor([[  3.,   6.],
        [  9.,  12.],
        [ 15.,  18.],
        [ 21.,  24.],
        [ 27.,  30.]])

In [109]:
print(res)

tensor([[  3.,   6.],
        [  9.,  12.],
        [ 15.,  18.],
        [ 21.,  24.],
        [ 27.,  30.]])


We can also carry out tensor mutations in-place. Methods that can do this are post-fixed with an `_`:

In [110]:
print(res.t_()) # transpose
res.copy_(x.t_())

tensor([[  3.,   9.,  15.,  21.,  27.],
        [  6.,  12.,  18.,  24.,  30.]])


tensor([[  1.,   3.,   5.,   7.,   9.],
        [  2.,   4.,   6.,   8.,  10.]])

Indexing is exactly the same as it is in Numpy:

In [111]:
x[1,:]

tensor([  2.,   4.,   6.,   8.,  10.])

Use `.item()` to obtain a single number as a python number

In [112]:
x[1, 2].item()

6.0

And convert Torch Tensors to Numpy ndarrays like this (Note: the numpy array stored in z is not immutable, as displayed. Change the value of x, and z changes too):

In [120]:
import numpy as np

z = x.numpy()
print("X as a numpy array, stored in Z:", z, sep="\n")
x.add_(1)
print("X now:", x, sep="\n")
print("Z has changed with X:", z, sep="\n")

X as a numpy array, stored in Z:
[[ 7.  9. 11. 13. 15.]
 [ 8. 10. 12. 14. 16.]]
X now:
tensor([[  8.,  10.,  12.,  14.,  16.],
        [  9.,  11.,  13.,  15.,  17.]])
Z has changed with X:
[[ 8. 10. 12. 14. 16.]
 [ 9. 11. 13. 15. 17.]]


You can also convert a Numpy array to a Tensor:

In [132]:
a = np.arange(12)
b = torch.from_numpy(a)
print(a, b, sep="\n")

np.add(a, 1, out=a)
print(a, b, sep="\n")

[ 0  1  2  3  4  5  6  7  8  9 10 11]
tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11], dtype=torch.int32)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12], dtype=torch.int32)


## CUDA Tensors

Tensors can be moved onto any device using the `to` method (which can also be used to change dtype):

In [3]:
x = torch.range(1, 100)
y = torch.range(101, 200)    

In [4]:
%time z = x + y
print(z)

Wall time: 996 µs
tensor([ 102.,  104.,  106.,  108.,  110.,  112.,  114.,  116.,  118.,
         120.,  122.,  124.,  126.,  128.,  130.,  132.,  134.,  136.,
         138.,  140.,  142.,  144.,  146.,  148.,  150.,  152.,  154.,
         156.,  158.,  160.,  162.,  164.,  166.,  168.,  170.,  172.,
         174.,  176.,  178.,  180.,  182.,  184.,  186.,  188.,  190.,
         192.,  194.,  196.,  198.,  200.,  202.,  204.,  206.,  208.,
         210.,  212.,  214.,  216.,  218.,  220.,  222.,  224.,  226.,
         228.,  230.,  232.,  234.,  236.,  238.,  240.,  242.,  244.,
         246.,  248.,  250.,  252.,  254.,  256.,  258.,  260.,  262.,
         264.,  266.,  268.,  270.,  272.,  274.,  276.,  278.,  280.,
         282.,  284.,  286.,  288.,  290.,  292.,  294.,  296.,  298.,
         300.])


In [6]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = x.to(device)
    y = y.to(device)

In [7]:
%time z = x + y

Wall time: 997 µs
